library(plumber)
pr  <- plumber$new()
first  <- plumber$new("first_file.R")
second <- plumber$new("second_file.R")
db <- plumber$new("database_connection.R")
# pr$mount("/", first)
pr$mount("/api", db)
# pr$run(port=8000, swagger=TRUE)
pr$run(port=8000, swagger=FALSE)
